In [1]:
import numpy as np

# Notes about numpy

## One-dimensional Arrays

In [2]:
one_dimensional_arr = np.array([10, 12])
print(one_dimensional_arr)

[10 12]


In [3]:
# Create an array with 3 integers, starting from the default integer 0.
b = np.arange(3)
print(b)

[0 1 2]


In [4]:
# Create an array that starts from the integer 1, ends at 20, incremented by 3.
c = np.arange(1, 20, 3)
print(c)

[ 1  4  7 10 13 16 19]


In [5]:
# Defaults to float
lin_spaced_arr = np.linspace(0, 100, 5)
print(lin_spaced_arr)

[  0.  25.  50.  75. 100.]


In [6]:
# Set as int
lin_spaced_arr_int = np.linspace(0, 100, 5, dtype=int)
print(lin_spaced_arr_int)

[  0  25  50  75 100]


In [7]:
# Return a new array of shape 3, filled with ones. 
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [8]:
# Return a new array of shape 3, filled with zeroes.
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [9]:
# Return a new array of shape 3, without initializing entries.
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


In [10]:
# Return a new array of shape 3 with random numbers between 0 and 1.
rand_arr = np.random.rand(3)
print(rand_arr)

[0.11200548 0.72475493 0.15062561]


## Multi-dimensional Arrays

In [11]:
# Create a 2 dimensional array (2-D)
two_dim_arr = np.array([[1,2,3], [4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


In [12]:
# 1-D array 
one_dim_arr = np.array([1, 2, 3, 4, 5, 6])

# Multidimensional array using reshape()
multi_dim_arr = np.reshape(
                one_dim_arr, # the array to be reshaped
               (2,3) # dimensions of the new array
              )
# Print the new 2-D array with two rows and three columns
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


## Array Meta Data

In [13]:
# Dimension of the 2-D array multi_dim_arr
multi_dim_arr.ndim

2

In [14]:
# Shape of the 2-D array multi_dim_arr
# Returns shape of 2 rows and 3 columns
multi_dim_arr.shape

(2, 3)

In [15]:
# Size of the array multi_dim_arr
# Returns total number of elements
multi_dim_arr.size

6

## Array Math Operations

In [16]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

# Adding two 1-D arrays
addition = arr_1 + arr_2
print(addition)

# Subtracting two 1-D arrays
subtraction = arr_1 - arr_2
print(subtraction)

# Multiplying two 1-D arrays elementwise
multiplication = arr_1 * arr_2
print(multiplication)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


In [17]:
# Broadcasting
vector = np.array([1, 2])
vector * 1.6

array([1.6, 3.2])

## Slicing

array[start:end:step]

In [18]:
# Slice the array a to get the array [2,3,4]
a = np.array([1, 2, 3, 4, 5])
sliced_arr = a[1:4]
print(sliced_arr)

[2 3 4]


In [19]:
# Slice the array a to get the array [1,2,3]
sliced_arr = a[:3]
print(sliced_arr)

[1 2 3]


In [20]:
# Slice the array a to get the array [3,4,5]
sliced_arr = a[2:]
print(sliced_arr)

[3 4 5]


In [21]:
# Slice the array a to get the array [1,3,5]
sliced_arr = a[::2]
print(sliced_arr)

[1 3 5]


## Stacking

In [22]:
a1 = np.array([[1,1], 
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [23]:
# Stack the arrays vertically
vert_stack = np.vstack((a1, a2))
print(vert_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [24]:
# Stack the arrays horizontally
horz_stack = np.hstack((a1, a2))
print(horz_stack)

[[1 1 3 3]
 [2 2 4 4]]
